package com.nyancoin.ABCBooks.Book;

import com.nyancoin.ABCBooks.Book.AuthorRepository;
import com.nyancoin.ABCBooks.Book.AuthorEntity;
import com.nyancoin.ABCBooks.Book.Author;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.beans.factory.annotation.Autowired;

@SpringBootApplication
@RestController
public class BookApplication {
	@Autowired // This means to get the bean called userRepository
			   // Which is auto-generated by Spring, we will use it to handle the data
	private AuthorRepository authorRepository;
	@Autowired
	private UserRepository userRepository;

	@Autowired
	private Author authorService;

	public static void main(String[] args) {		
		SpringApplication.run(BookApplication.class, args);
	}

	public BookApplication()
	{
		// Let spring create!
		//authorService = new Author(authorRepository);
	}

	@RequestMapping("/")
	public String index() {
		return "Greetings from ABC Books!";
	}
	
	@GetMapping("/hello")
	public String hello(@RequestParam(value = "name", defaultValue = "World") String name) {
		return String.format("Hello %s!", name);
	}
	
	@GetMapping(path="/all")
	public @ResponseBody Iterable<AuthorEntity> getAllAuthors() {
		return authorRepository.findAll();
	//public @ResponseBody Iterable<User> getAllUsers() {
	/*public String getAll() { // debugging version
		// This returns a JSON or XML with the users*/
		//return userRepository.findAll();
		/*String result;
		result = "";
		if (userRepository == null) {
			result += "userRepo null.<br>";
		}
		if (authorRepository == null) {
			result += "autorRepo null.<br>";
		}
		
		return result;*/
			
	}

	@RequestMapping("/addbook")
	public String addbook(@RequestParam(value = "author", defaultValue = "") String author,
						  @RequestParam(value = "title", defaultValue = "") String title) {
		String result = "";
		String form = "<form><label for=\"author\">Author</label><br><input type=\"text\" id=\"author\" name=\"author\" value=\"\" autofocus><br><label for=\"title\">Title</label><br><input type=\"text\" id=\"title\" name=\"title\" value=\"\"><br><br><input type=\"submit\" value=\"Submit\"></form>";
		
		if (author.isEmpty() && title.isEmpty()) {
			result = form;
		} else if (!(author.isEmpty()) && !(title.isEmpty())) {
			result = "Author: " + author + "; Title: " + title + "<br>";
			result += "*Beep boop* Database entry added! (Just a bit though.)";
			Integer aid = authorService.LookupOrAdd(author);
			result += "Author id comes back as: " + aid;
			result += "Book id comes back as: " + bookService.LookupOrAdd(aid, title);
			// TODO actually have database recording this
			// TODO check for obvious duplicate here
			result = result + "<br><br>" + form;
		} else {
			// Either author or title is set but not both.
			// This case should be handled with a default value setting in form to save what's been entered incompletely
			// TODO: Fix as per above; 
			result = "*Error* Only title or author but not both given. Case needs to be handled better (store prior given value).";
			result = result + "<br><br> Please retry. <br><br>" + form;

			// Kludge of repeating magic value of form with slight modifications.
			// TODO Ultimately have a form generation uio wrapper
			if (author.isEmpty()) {
				result = "Please specify a name of an author as well as the title.<br>";
				result += "<form><label for=\"author\">Author</label><br><input type=\"text\" id=\"author\" name=\"author\" value=\"\" autofocus><br><label for=\"title\">Title</label><br><input type=\"text\" id=\"title\" name=\"title\" value=\"";
				result += title;
				result += "\"><br><br><input type=\"submit\" value=\"Submit\"></form>";
		
			} else if (title.isEmpty()) {
				result = "Please specify the title of the work as well as its author.<br>";
				result += "<form><label for=\"author\">Author</label><br><input type=\"text\" id=\"author\" name=\"author\" value=\"";
				result += author;
				result += "\"><br><label for=\"title\">Title</label><br><input type=\"text\" id=\"title\" name=\"title\" value=\"\" autofocus><br><br><input type=\"submit\" value=\"Submit\"></form>";

			} else {
				// I believe I have already covered all possible cases.
				result = "Unexpected case reached internally.<br>";
				result += form;
			}
		}

		return result;
	}

}
