package com.nyancoin.ABCBooks.Book;

import com.nyancoin.ABCBooks.Book.AuthorRepository;
import com.nyancoin.ABCBooks.Book.AuthorEntity;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.beans.factory.annotation.Autowired;

@SpringBootApplication
@RestController
public class BookApplication {
	@Autowired // This means to get the bean called userRepository
			   // Which is auto-generated by Spring, we will use it to handle the data
	private AuthorRepository authorRepository;
	@Autowired
	private UserRepository userRepository;

	public static void main(String[] args) {
		SpringApplication.run(BookApplication.class, args);
	}

	@RequestMapping("/")
	public String index() {
		return "Greetings from ABC Books!";
	}
	
	@GetMapping("/hello")
	public String hello(@RequestParam(value = "name", defaultValue = "World") String name) {
		return String.format("Hello %s!", name);
	}
	
	@GetMapping(path="/all")
	public @ResponseBody Iterable<AuthorEntity> getAllAuthors() {
		return authorRepository.findAll();
	//public @ResponseBody Iterable<User> getAllUsers() {
	/*public String getAll() { // debugging version
		// This returns a JSON or XML with the users*/
		//return userRepository.findAll();
		/*String result;
		result = "";
		if (userRepository == null) {
			result += "userRepo null.<br>";
		}
		if (authorRepository == null) {
			result += "autorRepo null.<br>";
		}
		
		return result;*/
			
	}

}
